### ISSUE TITLE
retype step by step

### ISSUE THREAD

**Issue by faga1** [antfu/retypewriter#7]
### Clear and concise description of the problem

As a shareholder,I want retypewritter can retype step by step,I would like retypewritter can add a button  whenever the user click this button, it will retype only one snapshot.I intend to submit a PR for this issue.

### Suggested solution

Add a button in the menus  when etypewritter isplaying, if the user does not click the button, retypewriter will retype as common,if the user click it, retypewritter will stop when current snapshot is done.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by faga1** [comment]
maybe pause option can fulfill my expectation

**Comment by martiliones** [comment]
I didn't get it first, but if I could help someone, the author means to use `pause` option

The syntax is:
```
--<STEP NUMBER>----------

-----options--
pause: true
--<NEXT STEP>----------
```
so options are defined at the end of the block, after the block was triggered you need to press any button to continue

there also could be a bug when you need to restart VS Code to apply the changes
