### ISSUE TITLE
in vscode version 1.70.0 can't install

### ISSUE THREAD

**Issue by winner106** [antfu/retypewriter#8]
### Describe the bug

![image](https://user-images.githubusercontent.com/50519642/195033566-f1d1ebec-7cba-44f0-8455-83740db4098b.png)

### Reproduction

in vscode version 1.70.0 can't install

### System Info

```Shell
Version: 1.70.0 (user setup)
Commit: da76f93349a72022ca4670c1b84860304616aaa2
Date: 2022-08-04T04:38:16.462Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19044
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
https://github.com/antfu/retypewriter/blob/33b2447df25978d6eaea29cf684343b87b7d7432/packages/vscode/package.json#L25-L27
